//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Sequential2013", "SeqBookSeqChapter", "SeqBook", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sequential2013.Domain.SeqBook), "SeqChapter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqChapter), true)]
[assembly: EdmRelationshipAttribute("Sequential2013", "SeqChapterSeqPage", "SeqChapter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sequential2013.Domain.SeqChapter), "SeqPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqPage), true)]
[assembly: EdmRelationshipAttribute("Sequential2013", "SeqTagSeqPost", "SeqTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqTag), "SeqPost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqPost))]
[assembly: EdmRelationshipAttribute("Sequential2013", "SeqCategorySeqPost", "SeqCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Sequential2013.Domain.SeqCategory), "SeqPost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqPost))]
[assembly: EdmRelationshipAttribute("Sequential2013", "SeqPageSeqTag", "SeqPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqPage), "SeqTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sequential2013.Domain.SeqTag))]

#endregion

namespace Sequential2013.Domain
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SeqEFContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SeqEFContext object using the connection string found in the 'SeqEFContext' section of the application configuration file.
        /// </summary>
        public SeqEFContext() : base("name=SeqEFContext", "SeqEFContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeqEFContext object.
        /// </summary>
        public SeqEFContext(string connectionString) : base(connectionString, "SeqEFContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeqEFContext object.
        /// </summary>
        public SeqEFContext(EntityConnection connection) : base(connection, "SeqEFContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeqPage> SeqPages
        {
            get
            {
                if ((_SeqPages == null))
                {
                    _SeqPages = base.CreateObjectSet<SeqPage>("SeqPages");
                }
                return _SeqPages;
            }
        }
        private ObjectSet<SeqPage> _SeqPages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeqChapter> SeqChapters
        {
            get
            {
                if ((_SeqChapters == null))
                {
                    _SeqChapters = base.CreateObjectSet<SeqChapter>("SeqChapters");
                }
                return _SeqChapters;
            }
        }
        private ObjectSet<SeqChapter> _SeqChapters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeqBook> SeqBooks
        {
            get
            {
                if ((_SeqBooks == null))
                {
                    _SeqBooks = base.CreateObjectSet<SeqBook>("SeqBooks");
                }
                return _SeqBooks;
            }
        }
        private ObjectSet<SeqBook> _SeqBooks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeqPost> SeqPosts
        {
            get
            {
                if ((_SeqPosts == null))
                {
                    _SeqPosts = base.CreateObjectSet<SeqPost>("SeqPosts");
                }
                return _SeqPosts;
            }
        }
        private ObjectSet<SeqPost> _SeqPosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeqTag> SeqTags
        {
            get
            {
                if ((_SeqTags == null))
                {
                    _SeqTags = base.CreateObjectSet<SeqTag>("SeqTags");
                }
                return _SeqTags;
            }
        }
        private ObjectSet<SeqTag> _SeqTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeqCategory> SeqCategories
        {
            get
            {
                if ((_SeqCategories == null))
                {
                    _SeqCategories = base.CreateObjectSet<SeqCategory>("SeqCategories");
                }
                return _SeqCategories;
            }
        }
        private ObjectSet<SeqCategory> _SeqCategories;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeqPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeqPages(SeqPage seqPage)
        {
            base.AddObject("SeqPages", seqPage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeqChapters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeqChapters(SeqChapter seqChapter)
        {
            base.AddObject("SeqChapters", seqChapter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeqBooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeqBooks(SeqBook seqBook)
        {
            base.AddObject("SeqBooks", seqBook);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeqPosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeqPosts(SeqPost seqPost)
        {
            base.AddObject("SeqPosts", seqPost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeqTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeqTags(SeqTag seqTag)
        {
            base.AddObject("SeqTags", seqTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeqCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeqCategories(SeqCategory seqCategory)
        {
            base.AddObject("SeqCategories", seqCategory);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sequential2013", Name="SeqBook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeqBook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeqBook object.
        /// </summary>
        /// <param name="bookId">Initial value of the BookId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="pageCount">Initial value of the PageCount property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        /// <param name="uriContext">Initial value of the UriContext property.</param>
        public static SeqBook CreateSeqBook(global::System.Int32 bookId, global::System.String title, global::System.Int32 pageCount, global::System.DateTime lastUpdated, global::System.String uriContext)
        {
            SeqBook seqBook = new SeqBook();
            seqBook.BookId = bookId;
            seqBook.Title = title;
            seqBook.PageCount = pageCount;
            seqBook.LastUpdated = lastUpdated;
            seqBook.UriContext = uriContext;
            return seqBook;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookId
        {
            get
            {
                return _BookId;
            }
            set
            {
                if (_BookId != value)
                {
                    OnBookIdChanging(value);
                    ReportPropertyChanging("BookId");
                    _BookId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookId");
                    OnBookIdChanged();
                }
            }
        }
        private global::System.Int32 _BookId;
        partial void OnBookIdChanging(global::System.Int32 value);
        partial void OnBookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageCount
        {
            get
            {
                return _PageCount;
            }
            set
            {
                OnPageCountChanging(value);
                ReportPropertyChanging("PageCount");
                _PageCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageCount");
                OnPageCountChanged();
            }
        }
        private global::System.Int32 _PageCount;
        partial void OnPageCountChanging(global::System.Int32 value);
        partial void OnPageCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UriContext
        {
            get
            {
                return _UriContext;
            }
            set
            {
                OnUriContextChanging(value);
                ReportPropertyChanging("UriContext");
                _UriContext = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UriContext");
                OnUriContextChanged();
            }
        }
        private global::System.String _UriContext;
        partial void OnUriContextChanging(global::System.String value);
        partial void OnUriContextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CoverImage
        {
            get
            {
                return _CoverImage;
            }
            set
            {
                OnCoverImageChanging(value);
                ReportPropertyChanging("CoverImage");
                _CoverImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CoverImage");
                OnCoverImageChanged();
            }
        }
        private global::System.String _CoverImage;
        partial void OnCoverImageChanging(global::System.String value);
        partial void OnCoverImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqBookSeqChapter", "SeqChapter")]
        public EntityCollection<SeqChapter> SeqChapters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqChapter>("Sequential2013.SeqBookSeqChapter", "SeqChapter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqChapter>("Sequential2013.SeqBookSeqChapter", "SeqChapter", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sequential2013", Name="SeqCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeqCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeqCategory object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="tally">Initial value of the Tally property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        /// <param name="blogId">Initial value of the BlogId property.</param>
        public static SeqCategory CreateSeqCategory(global::System.Int32 categoryId, global::System.String name, global::System.Int32 tally, global::System.DateTime lastUpdated, global::System.String blogId)
        {
            SeqCategory seqCategory = new SeqCategory();
            seqCategory.CategoryId = categoryId;
            seqCategory.Name = name;
            seqCategory.Tally = tally;
            seqCategory.LastUpdated = lastUpdated;
            seqCategory.BlogId = blogId;
            return seqCategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tally
        {
            get
            {
                return _Tally;
            }
            set
            {
                OnTallyChanging(value);
                ReportPropertyChanging("Tally");
                _Tally = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tally");
                OnTallyChanged();
            }
        }
        private global::System.Int32 _Tally;
        partial void OnTallyChanging(global::System.Int32 value);
        partial void OnTallyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                OnBlogIdChanging(value);
                ReportPropertyChanging("BlogId");
                _BlogId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BlogId");
                OnBlogIdChanged();
            }
        }
        private global::System.String _BlogId;
        partial void OnBlogIdChanging(global::System.String value);
        partial void OnBlogIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqCategorySeqPost", "SeqPost")]
        public EntityCollection<SeqPost> SeqPosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqPost>("Sequential2013.SeqCategorySeqPost", "SeqPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqPost>("Sequential2013.SeqCategorySeqPost", "SeqPost", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sequential2013", Name="SeqChapter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeqChapter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeqChapter object.
        /// </summary>
        /// <param name="chapterId">Initial value of the ChapterId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="seqBookBookId">Initial value of the SeqBookBookId property.</param>
        /// <param name="pageCount">Initial value of the PageCount property.</param>
        public static SeqChapter CreateSeqChapter(global::System.Int32 chapterId, global::System.String title, global::System.Int32 seqBookBookId, global::System.Int32 pageCount)
        {
            SeqChapter seqChapter = new SeqChapter();
            seqChapter.ChapterId = chapterId;
            seqChapter.Title = title;
            seqChapter.SeqBookBookId = seqBookBookId;
            seqChapter.PageCount = pageCount;
            return seqChapter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChapterId
        {
            get
            {
                return _ChapterId;
            }
            set
            {
                if (_ChapterId != value)
                {
                    OnChapterIdChanging(value);
                    ReportPropertyChanging("ChapterId");
                    _ChapterId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChapterId");
                    OnChapterIdChanged();
                }
            }
        }
        private global::System.Int32 _ChapterId;
        partial void OnChapterIdChanging(global::System.Int32 value);
        partial void OnChapterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChapterNum
        {
            get
            {
                return _ChapterNum;
            }
            set
            {
                OnChapterNumChanging(value);
                ReportPropertyChanging("ChapterNum");
                _ChapterNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChapterNum");
                OnChapterNumChanged();
            }
        }
        private Nullable<global::System.Int32> _ChapterNum;
        partial void OnChapterNumChanging(Nullable<global::System.Int32> value);
        partial void OnChapterNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeqBookBookId
        {
            get
            {
                return _SeqBookBookId;
            }
            set
            {
                OnSeqBookBookIdChanging(value);
                ReportPropertyChanging("SeqBookBookId");
                _SeqBookBookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeqBookBookId");
                OnSeqBookBookIdChanged();
            }
        }
        private global::System.Int32 _SeqBookBookId;
        partial void OnSeqBookBookIdChanging(global::System.Int32 value);
        partial void OnSeqBookBookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageCount
        {
            get
            {
                return _PageCount;
            }
            set
            {
                OnPageCountChanging(value);
                ReportPropertyChanging("PageCount");
                _PageCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageCount");
                OnPageCountChanged();
            }
        }
        private global::System.Int32 _PageCount;
        partial void OnPageCountChanging(global::System.Int32 value);
        partial void OnPageCountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqBookSeqChapter", "SeqBook")]
        public SeqBook SeqBook
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqBook>("Sequential2013.SeqBookSeqChapter", "SeqBook").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqBook>("Sequential2013.SeqBookSeqChapter", "SeqBook").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SeqBook> SeqBookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqBook>("Sequential2013.SeqBookSeqChapter", "SeqBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SeqBook>("Sequential2013.SeqBookSeqChapter", "SeqBook", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqChapterSeqPage", "SeqPage")]
        public EntityCollection<SeqPage> SeqPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqPage>("Sequential2013.SeqChapterSeqPage", "SeqPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqPage>("Sequential2013.SeqChapterSeqPage", "SeqPage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sequential2013", Name="SeqPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeqPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeqPage object.
        /// </summary>
        /// <param name="pageId">Initial value of the PageId property.</param>
        /// <param name="seqChapterChapterId">Initial value of the SeqChapterChapterId property.</param>
        public static SeqPage CreateSeqPage(global::System.Int32 pageId, global::System.Int32 seqChapterChapterId)
        {
            SeqPage seqPage = new SeqPage();
            seqPage.PageId = pageId;
            seqPage.SeqChapterChapterId = seqChapterChapterId;
            return seqPage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageId
        {
            get
            {
                return _PageId;
            }
            set
            {
                if (_PageId != value)
                {
                    OnPageIdChanging(value);
                    ReportPropertyChanging("PageId");
                    _PageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PageId");
                    OnPageIdChanged();
                }
            }
        }
        private global::System.Int32 _PageId;
        partial void OnPageIdChanging(global::System.Int32 value);
        partial void OnPageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> PageNum
        {
            get
            {
                return _PageNum;
            }
            set
            {
                OnPageNumChanging(value);
                ReportPropertyChanging("PageNum");
                _PageNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageNum");
                OnPageNumChanged();
            }
        }
        private Nullable<global::System.Int16> _PageNum;
        partial void OnPageNumChanging(Nullable<global::System.Int16> value);
        partial void OnPageNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeqChapterChapterId
        {
            get
            {
                return _SeqChapterChapterId;
            }
            set
            {
                OnSeqChapterChapterIdChanging(value);
                ReportPropertyChanging("SeqChapterChapterId");
                _SeqChapterChapterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeqChapterChapterId");
                OnSeqChapterChapterIdChanged();
            }
        }
        private global::System.Int32 _SeqChapterChapterId;
        partial void OnSeqChapterChapterIdChanging(global::System.Int32 value);
        partial void OnSeqChapterChapterIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqChapterSeqPage", "SeqChapter")]
        public SeqChapter SeqChapter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqChapter>("Sequential2013.SeqChapterSeqPage", "SeqChapter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqChapter>("Sequential2013.SeqChapterSeqPage", "SeqChapter").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SeqChapter> SeqChapterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqChapter>("Sequential2013.SeqChapterSeqPage", "SeqChapter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SeqChapter>("Sequential2013.SeqChapterSeqPage", "SeqChapter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqPageSeqTag", "SeqTag")]
        public EntityCollection<SeqTag> SeqTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqTag>("Sequential2013.SeqPageSeqTag", "SeqTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqTag>("Sequential2013.SeqPageSeqTag", "SeqTag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sequential2013", Name="SeqPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeqPost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeqPost object.
        /// </summary>
        /// <param name="postId">Initial value of the PostId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="published">Initial value of the Published property.</param>
        public static SeqPost CreateSeqPost(global::System.Int32 postId, global::System.String title, global::System.DateTime createDate, global::System.Boolean published)
        {
            SeqPost seqPost = new SeqPost();
            seqPost.PostId = postId;
            seqPost.Title = title;
            seqPost.CreateDate = createDate;
            seqPost.Published = published;
            return seqPost;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostId
        {
            get
            {
                return _PostId;
            }
            set
            {
                if (_PostId != value)
                {
                    OnPostIdChanging(value);
                    ReportPropertyChanging("PostId");
                    _PostId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostId");
                    OnPostIdChanged();
                }
            }
        }
        private global::System.Int32 _PostId;
        partial void OnPostIdChanging(global::System.Int32 value);
        partial void OnPostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Published
        {
            get
            {
                return _Published;
            }
            set
            {
                OnPublishedChanging(value);
                ReportPropertyChanging("Published");
                _Published = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Published");
                OnPublishedChanged();
            }
        }
        private global::System.Boolean _Published;
        partial void OnPublishedChanging(global::System.Boolean value);
        partial void OnPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Excerpt
        {
            get
            {
                return _Excerpt;
            }
            set
            {
                OnExcerptChanging(value);
                ReportPropertyChanging("Excerpt");
                _Excerpt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Excerpt");
                OnExcerptChanged();
            }
        }
        private global::System.String _Excerpt;
        partial void OnExcerptChanging(global::System.String value);
        partial void OnExcerptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtendedText
        {
            get
            {
                return _ExtendedText;
            }
            set
            {
                OnExtendedTextChanging(value);
                ReportPropertyChanging("ExtendedText");
                _ExtendedText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtendedText");
                OnExtendedTextChanged();
            }
        }
        private global::System.String _ExtendedText;
        partial void OnExtendedTextChanging(global::System.String value);
        partial void OnExtendedTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Permalink
        {
            get
            {
                return _Permalink;
            }
            set
            {
                OnPermalinkChanging(value);
                ReportPropertyChanging("Permalink");
                _Permalink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Permalink");
                OnPermalinkChanged();
            }
        }
        private global::System.String _Permalink;
        partial void OnPermalinkChanging(global::System.String value);
        partial void OnPermalinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                OnBlogIdChanging(value);
                ReportPropertyChanging("BlogId");
                _BlogId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BlogId");
                OnBlogIdChanged();
            }
        }
        private global::System.String _BlogId;
        partial void OnBlogIdChanging(global::System.String value);
        partial void OnBlogIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqTagSeqPost", "SeqTag")]
        public EntityCollection<SeqTag> SeqTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqTag>("Sequential2013.SeqTagSeqPost", "SeqTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqTag>("Sequential2013.SeqTagSeqPost", "SeqTag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqCategorySeqPost", "SeqCategory")]
        public SeqCategory SeqCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqCategory>("Sequential2013.SeqCategorySeqPost", "SeqCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqCategory>("Sequential2013.SeqCategorySeqPost", "SeqCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SeqCategory> SeqCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeqCategory>("Sequential2013.SeqCategorySeqPost", "SeqCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SeqCategory>("Sequential2013.SeqCategorySeqPost", "SeqCategory", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sequential2013", Name="SeqTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeqTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeqTag object.
        /// </summary>
        /// <param name="tagId">Initial value of the TagId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        /// <param name="tally">Initial value of the Tally property.</param>
        /// <param name="blogId">Initial value of the BlogId property.</param>
        public static SeqTag CreateSeqTag(global::System.Int32 tagId, global::System.String name, global::System.DateTime lastUpdated, global::System.Int32 tally, global::System.String blogId)
        {
            SeqTag seqTag = new SeqTag();
            seqTag.TagId = tagId;
            seqTag.Name = name;
            seqTag.LastUpdated = lastUpdated;
            seqTag.Tally = tally;
            seqTag.BlogId = blogId;
            return seqTag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                if (_TagId != value)
                {
                    OnTagIdChanging(value);
                    ReportPropertyChanging("TagId");
                    _TagId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagId");
                    OnTagIdChanged();
                }
            }
        }
        private global::System.Int32 _TagId;
        partial void OnTagIdChanging(global::System.Int32 value);
        partial void OnTagIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tally
        {
            get
            {
                return _Tally;
            }
            set
            {
                OnTallyChanging(value);
                ReportPropertyChanging("Tally");
                _Tally = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tally");
                OnTallyChanged();
            }
        }
        private global::System.Int32 _Tally;
        partial void OnTallyChanging(global::System.Int32 value);
        partial void OnTallyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                OnBlogIdChanging(value);
                ReportPropertyChanging("BlogId");
                _BlogId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BlogId");
                OnBlogIdChanged();
            }
        }
        private global::System.String _BlogId;
        partial void OnBlogIdChanging(global::System.String value);
        partial void OnBlogIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqTagSeqPost", "SeqPost")]
        public EntityCollection<SeqPost> SeqPosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqPost>("Sequential2013.SeqTagSeqPost", "SeqPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqPost>("Sequential2013.SeqTagSeqPost", "SeqPost", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sequential2013", "SeqPageSeqTag", "SeqPage")]
        public EntityCollection<SeqPage> SeqPage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeqPage>("Sequential2013.SeqPageSeqTag", "SeqPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeqPage>("Sequential2013.SeqPageSeqTag", "SeqPage", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
